/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#3a494b',
        'primary-container': '#00f2ff',
        'on-primary': '#00363a',
        'error': '#ffb4ab',
        'surface-dim': '#0d1515',
        'on-tertiary-fixed-variant': '#544600',
        'tertiary-container': '#ffd81d',
        'on-primary-fixed-variant': '#004f54',
        'tertiary-fixed': '#ffe16d',
        'outline': '#849495',
        'surface-container-lowest': '#080f10',
        'surface-container-high': '#232b2c',
        'secondary-fixed-dim': '#ffabf3',
        'surface-tint': '#00dbe7',
        'tertiary-fixed-dim': '#e9c400',
        'on-primary-fixed': '#002022',
        'primary': '#e1fdff',
        'on-surface': '#dce4e4',
        'secondary-fixed': '#ffd7f5',
        'surface-variant': '#2e3637',
        'on-secondary': '#5b005b',
        'on-surface-variant': '#b9cacb',
        'on-error-container': '#ffdad6',
        'tertiary': '#fff6e4',
        'on-background': '#dce4e4',
        'surface-container-low': '#151d1e',
        'on-secondary-fixed': '#380038',
        'background': '#0d1515',
        'surface-bright': '#333b3b',
        'on-secondary-fixed-variant': '#810081',
        'secondary-container': '#fe00fe',
        'inverse-on-surface': '#2a3232',
        'error-container': '#93000a',
        'inverse-primary': '#00696f',
        'primary-fixed': '#74f5ff',
        'on-tertiary-fixed': '#221b00',
        'on-error': '#690005',
        'on-tertiary': '#3a3000',
        'primary-fixed-dim': '#00dbe7',
        'on-primary-container': '#006a71',
        'surface-container-highest': '#2e3637',
        'surface': '#0d1515',
        'on-tertiary-container': '#715e00',
        'on-secondary-container': '#500050',
        'secondary': '#ffabf3',
        'surface-container': '#192122',
        'inverse-surface': '#dce4e4',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '48px',
        'container-margin': '20px',
        gutter: '16px',
        unit: '4px',
      },
      fontFamily: {
        'body-md': ['Sora', 'sans-serif'],
        'label-caps': ['Space Mono', 'monospace'],
        'display-hero': ['EB Garamond', 'serif'],
        'headline-lg-mobile': ['EB Garamond', 'serif'],
        'data-readout': ['Space Mono', 'monospace'],
        'headline-lg': ['EB Garamond', 'serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '700' }],
        'display-hero': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '500' }],
        'data-readout': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
